### ISSUE TITLE
Checklist UML

### ISSUE THREAD

**Issue by andrearoota** [andrearoota/SoftwareEngineeringProject#20]
### Documentazione necessaria
Utilizziamo questo issue per tenere traccia della documentazione necessaria al progetto:

- [x] Project plan
- [x] Diagramma casi d'uso (@andrearoota)
- [x] Diagramma delle classi (@andrearoota)
- [x] Diagramma di sequenza 01 (@CamillaMazzoleni)
- [x] Diagramma di sequenza 02 (@mattcolo01)
- [x] Diagramma di stato 01 (@CamillaMazzoleni)
- [x] Diagramma di stato 02 (@pierGit7)
- [x] Diagramma delle attività 01 (@pierGit7)
- [x] Diagramma delle attività 02 (@mattcolo01)
